git:
  commit:
    number: ${git.commit.id.abbrev}
application:
  version: ${project.version}
alpaca:
  commands:
    store: ${alpaca.basedir}/commands/

---

spring:
  config:
    activate:
      on-profile: win
alpaca:
  basedir: c:/alpaca

---

spring:
  config:
    activate:
      on-profile: mac
alpaca:
  basedir: ${user.home}/Library/Application Support/alpaca
